import { Metadata } from "next";
import LoginForm from "./login-form";

export const metadata: Metadata = {
  title: "Login | Nmesoma's Blog Admin",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <main>
      <LoginForm />
    </main>
  )
}
