import Search from "@/components/search";
import AddTag from "@/components/dashboard/tags/add-tag";
import { Metadata } from "next";
import TagsSection from "@/components/dashboard/tags/tags";

export const metadata: Metadata = {
  title: "Tags | Nmesoma's Blog Admin",
  description: "Generated by create next app",
}

export default async function Blogs({ searchParams }: { searchParams: { [key: string]: string | number } }) {
  const params = {
    limit: 5,
    ...searchParams
  }

  return (
    <main className="px-4 lg:px-10">
      <section className="pt-12 flex items-center justify-between">
        <h2 className="text-2xl md:text-4xl font-bold text-accent">All Tags</h2>
        <AddTag />
      </section>
      <section className="max-w-4xl mx-auto py-8 space-y-3 md:space-y-5">
        <Search placeholder="Search for tags....." />
        <TagsSection queryParams={params} />
      </section>
    </main>
  );
}

