import { Metadata } from "next";
import SignUpForm from "./signup-form";

export const metadata: Metadata = {
  title: "Sign Up | Nmesoma's Blog Admin",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <main>
      <SignUpForm />
    </main>
  )
}
