import { Metadata } from "next";
import ResetPasswordForm from "./reset-password-form";

export const metadata: Metadata = {
  title: "Reset Password | Choronovault",
  description: "Generated by create next app",
};

export default function ResetPassword() {
  return (
    <main>
      <ResetPasswordForm />
    </main>
  )
}
