import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Nmesoma's Blog Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="lg:max-w-7xl mx-auto  antialiased bg-[#FAFAFA] text-[#333333] font-leagueSpartan">
        <Toaster />
        {children}
      </body>
    </html>
  );
}
