import AppHeader from "@/components/dashboard/app-header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Settings - Dashboard | Choronovault",
  description: "Generated by create next app",
};

export default function Settings() {
  return (
    <main className="px-2 md:px-4 lg:px-10">
      <AppHeader title="Settings" />
      <div className="p-4">
        Hey from dashboard settings
      </div>
    </main>
  )
}
