import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home - Dashboard | NmesomaHenry's blog",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="px-4 lg:px-10">
      <div className="p-4">
        Hey from dashboard home
      </div>
    </main>
  )
}
